import { upsertCategory, upsertCategoryItem } from './db';

// Seed initial categories based on the hardcoded data from App.tsx
const seedData = [
    {
        id: 'launch-readiness',
        title: 'Launch Readiness',
        icon: 'Rocket',
        accent: 'from-grokPurple via-grokPink to-grokBlue',
        sort_order: 0,
        items: [
            { id: 'lr-1', title: 'Telemetry looks nominal', description: 'Latest staging checks passed with 98.6% health.', emphasis: 1, updated_at: '2m ago', sort_order: 0 },
            { id: 'lr-2', title: 'Crew comms lag detected', description: 'Latency spike from Sydney relay window.', emphasis: 0, updated_at: '4m ago', sort_order: 1 },
            { id: 'lr-3', title: 'Fuel mix variance 0.7%', description: 'Well within launch corridor tolerance.', emphasis: 0, updated_at: '6m ago', sort_order: 2 }
        ]
    },
    {
        id: 'incident-digest',
        title: 'Incident Digest',
        icon: 'Aperture',
        accent: 'from-grokBlue via-grokPurple to-grokPink',
        sort_order: 1,
        items: [
            { id: 'id-1', title: 'Model drift alert', description: 'Conversational tone shifting in APAC segment.', emphasis: 0, updated_at: '10m ago', sort_order: 0 },
            { id: 'id-2', title: 'Latency degrade risk', description: 'Vector cache eviction rate up 18%.', emphasis: 1, updated_at: '12m ago', sort_order: 1 },
            { id: 'id-3', title: 'Support backlog', description: 'Flagged threads for escalation review.', emphasis: 0, updated_at: null, sort_order: 2 }
        ]
    },
    {
        id: 'research-scout',
        title: 'Research Scout',
        icon: 'CircuitBoard',
        accent: 'from-grokPink via-grokBlue to-grokPurple',
        sort_order: 2,
        items: [
            { id: 'rs-1', title: 'Multi-agent planner paper', description: 'Arxiv 2412.101 pending peer review.', emphasis: 0, updated_at: '1h ago', sort_order: 0 },
            { id: 'rs-2', title: 'Competitor launch notes', description: 'Synthesized highlights from Nova One demo.', emphasis: 0, updated_at: null, sort_order: 1 },
            { id: 'rs-3', title: 'Pricing experimentation log', description: 'Tag with "growth" to pin results.', emphasis: 0, updated_at: null, sort_order: 2 }
        ]
    },
    {
        id: 'field-intel',
        title: 'Field Intelligence',
        icon: 'Compass',
        accent: 'from-grokBlue via-grokGreen to-grokPurple',
        sort_order: 3,
        items: [
            { id: 'fi-1', title: 'Customer sentiment swing', description: 'Healthcare pilots leaning toward premium tier.', emphasis: 1, updated_at: null, sort_order: 0 },
            { id: 'fi-2', title: 'Partner beta feedback', description: 'Edge cases from robotics integration stream.', emphasis: 0, updated_at: null, sort_order: 1 },
            { id: 'fi-3', title: 'Top requested features', description: 'Studio mode, multi-modal logging, agent replay.', emphasis: 0, updated_at: null, sort_order: 2 }
        ]
    },
    {
        id: 'team-os',
        title: 'Team OS',
        icon: 'Share2',
        accent: 'from-grokPurple via-grokBlue to-grokGreen',
        sort_order: 4,
        items: [
            { id: 'os-1', title: 'Handoff checklist', description: 'Bring ops playbook into next sync.', emphasis: 0, updated_at: '30m ago', sort_order: 0 },
            { id: 'os-2', title: 'Escalation ladder', description: 'Autogenerated from last incident reviews.', emphasis: 0, updated_at: null, sort_order: 1 },
            { id: 'os-3', title: 'Ops rituals', description: 'Daily review, weekly retro, monthly deep dive.', emphasis: 0, updated_at: null, sort_order: 2 }
        ]
    }
];

console.log('Seeding categories and items...');

for (const cat of seedData) {
    upsertCategory({
        id: cat.id,
        title: cat.title,
        icon: cat.icon,
        accent: cat.accent,
        sort_order: cat.sort_order
    });

    for (const item of cat.items) {
        upsertCategoryItem({
            id: item.id,
            category_id: cat.id,
            title: item.title,
            description: item.description,
            emphasis: item.emphasis,
            updated_at: item.updated_at,
            sort_order: item.sort_order
        });
    }
}

console.log('✅ Seeded', seedData.length, 'categories with items.');
